name = "wg-localization"
subteam-of = "community"
wg = true

[people]
leads = ["sebasmagri"]
members = [
    "sebasmagri",
    "Manishearth",
]

[website]
name = "Localization WG"
description = "Coordinating localization of various resources across languages"
discord-invite = "https://discord.gg/cj5HMXA"
discord-name = "#community-team"
